#pragma once
/*
class Game;

//This interface is generated by the Game-Objects twice. 
//The player gets this interface-object everytime it has to make a move
class GamePlayerInterface
{
private:
    Game& game;
    unsigned int player;        //Player number
public:
    GamePlayerInterface(Game& game, unsigned int player);
};*/

